### ISSUE TITLE
add exclude to skip files.

### ISSUE THREAD

**Issue by WeslleyDeSouza** [Quilljou/transmart#2]
module.exports = {
  baseLocale: "",
  locales: [""],
  localePath: "",
  openAIApiKey: "",
  overrides: {},
  exclude:[]
};

**Comment by Quilljou** [comment]
namespaceGlob option can do this job

**Comment by Quilljou** [comment]
> namespaceGlob option can do this job

seems not working in glob documention，I will resolve it later

**Comment by Quilljou** [comment]
```
  baseLocale: 'en',
  locales: ['zh-CN', 'zh-TW'],
  namespaceGlob: ['!(common.json)']
```
Try setting it up like this. @WeslleyDeSouza 。Also, I have already updated the readme.md。learn more about [glob](https://www.npmjs.com/package/glob#globprimer:~:text=!(pattern%7Cpattern%7Cpattern))
